# Generated by Django 5.1.15 on 2026-07-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_healthfacility_chatmessage_engine_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthfacility',
            old_name='ward',
            new_name='village',
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='country',
            field=models.CharField(default='Kenya', max_length=100),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
