package com.example.afyagpt.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * PatientEntity.kt
 *
 * Room database entity representing a patient tailored for triage and CHW workflow.
 */
@Entity(
    tableName = "patients",
    indices = [Index(value = ["patient_uid"], unique = true)]
)
data class PatientEntity(
    /** Primary key, auto-generated by Room. */
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    
    /** Unique identifier for the patient (e.g. AFYA-20260724-XXXX or RE-XXXXX). */
    @ColumnInfo(name = "patient_uid") val patientUid: String,
    
    /** Full name of the patient. */
    @ColumnInfo(name = "full_name") val fullName: String,
    
    /** Date of birth in ISO date format (YYYY-MM-DD). */
    @ColumnInfo(name = "date_of_birth") val dateOfBirth: String,
    
    /** Sex of the patient, e.g. MALE / FEMALE. */
    @ColumnInfo(name = "sex") val sex: String,
    
    /** Optional Birth Certificate Number. */
    @ColumnInfo(name = "birth_certificate_number") val birthCertificateNumber: String? = null,
    
    /** Contact phone number. */
    @ColumnInfo(name = "phone_number") val phoneNumber: String? = null,
    
    /** Name of the primary guardian/parent (essential for minors/triage). */
    @ColumnInfo(name = "caregiver_name") val caregiverName: String? = null,

    /** Guardian phone number. */
    @ColumnInfo(name = "guardian_phone") val guardianPhone: String? = null,

    /** Guardian relationship (e.g., Mother, Father, Guardian, Relative). */
    @ColumnInfo(name = "guardian_relation") val guardianRelation: String? = null,
    
    /** Village name of the patient. */
    @ColumnInfo(name = "village") val village: String? = null,
    
    /** Sub-location of the patient. */
    @ColumnInfo(name = "sub_location") val subLocation: String? = null,
    
    /** County of the patient. */
    @ColumnInfo(name = "county") val county: String? = null,
    
    /** Household ID of the patient. */
    @ColumnInfo(name = "household_id") val householdId: Int? = null,
    
    /** Risk level of the patient: LOW/MEDIUM/HIGH/CRITICAL. */
    @ColumnInfo(name = "risk_level") val riskLevel: String = "LOW",
    
    /** Malaria risk zone, defaults to HIGH. */
    @ColumnInfo(name = "malaria_risk_zone") val malariaRiskZone: String = "HIGH",
    
    /** ID of the user who registered this patient (foreign key to users.id). */
    @ColumnInfo(name = "registered_by") val registeredBy: Int,
    
    /** Name of the facility where registered (auto-filled from user but editable). */
    @ColumnInfo(name = "facility_name") val facilityName: String,
    
    /** Whether the patient is active. */
    @ColumnInfo(name = "is_active") val isActive: Boolean = true,
    
    /** Additional notes or triage observation hints. */
    @ColumnInfo(name = "notes") val notes: String? = null,
    
    /** Timestamp when the record was created. */
    @ColumnInfo(name = "created_at") val createdAt: String,
    
    /** Timestamp when the record was last updated. */
    @ColumnInfo(name = "updated_at") val updatedAt: String,
    
    /** Indicates if the record has been synced to the remote server. */
    @ColumnInfo(name = "is_synced") val isSynced: Boolean = false
)
