package com.example.afyagpt.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Entity representing a triage session in the local database.
 */
@Entity(tableName = "triage_sessions")
data class TriageSessionEntity(
    /** Primary key, auto-generated by Room. */
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    
    /** Unique identifier for the triage session, e.g. TRG-YYYYMMDD-XXXX. */
    @ColumnInfo(name = "session_uid") val sessionUid: String,
    
    /** Foreign key to the patient. */
    @ColumnInfo(name = "patient_id") val patientId: Int,
    
    /** Foreign key to the user who assessed the patient. */
    @ColumnInfo(name = "assessed_by") val assessedBy: Int,
    
    /** Danger sign: unable to drink or breastfeed. */
    @ColumnInfo(name = "unable_to_drink") val unableToDrink: Boolean = false,
    
    /** Danger sign: vomiting everything. */
    @ColumnInfo(name = "vomiting_everything") val vomitingEverything: Boolean = false,
    
    /** Danger sign: convulsions. */
    @ColumnInfo(name = "convulsions") val convulsions: Boolean = false,
    
    /** Danger sign: lethargic or unconscious. */
    @ColumnInfo(name = "lethargic") val lethargic: Boolean = false,
    
    /** Weight of the patient in kilograms. */
    @ColumnInfo(name = "weight_kg") val weightKg: Float?,
    
    /** Temperature of the patient in Celsius. */
    @ColumnInfo(name = "temperature_c") val temperatureC: Float?,
    
    /** Respiratory rate of the patient (breaths per minute). */
    @ColumnInfo(name = "resp_rate") val respRate: Int?,
    
    /** MUAC (Mid-Upper Arm Circumference) in millimeters. */
    @ColumnInfo(name = "muac_mm") val muacMm: Int?,
    
    /** Classification for respiratory symptoms. */
    @ColumnInfo(name = "respiratory_class") val respiratoryClass: String?,
    
    /** Classification for diarrhea symptoms. */
    @ColumnInfo(name = "diarrhea_class") val diarrheaClass: String?,
    
    /** Classification for fever symptoms. */
    @ColumnInfo(name = "fever_class") val feverClass: String?,
    
    /** Classification for ear problems. */
    @ColumnInfo(name = "ear_class") val earClass: String?,
    
    /** Classification for nutritional status. */
    @ColumnInfo(name = "nutrition_class") val nutritionClass: String?,
    
    /** Overall risk determined during triage. */
    @ColumnInfo(name = "overall_risk") val overallRisk: String = "LOW",
    
    /** Raw assessment fields stored as JSON string. */
    @ColumnInfo(name = "assessment_json") val assessmentJson: String? = null,
    
    /** Treatment plan stored as JSON string. */
    @ColumnInfo(name = "treatment_plan_json") val treatmentPlanJson: String? = null,
    
    /** Counseling information stored as JSON string. */
    @ColumnInfo(name = "counseling_json") val counselingJson: String? = null,
    
    /** Whether referral is needed. */
    @ColumnInfo(name = "referral_needed") val referralNeedeed: Boolean = false,
    
    /** Follow-up date if scheduled. */
    @ColumnInfo(name = "follow_up_date") val followUpDate: String? = null,
    
    /** Additional notes for the session. */
    @ColumnInfo(name = "notes") val notes: String? = null,
    
    /** Timestamp when the record was created. */
    @ColumnInfo(name = "created_at") val createdAt: String,
    
    /** Indicates if the record has been synced to the remote server. */
    @ColumnInfo(name = "is_synced") val isSynced: Boolean = false
)
