package com.example.afyagpt.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Entity representing a vaccination record in the local database.
 */
@Entity(tableName = "vaccinations")
data class VaccinationEntity(
    /** Primary key, auto-generated by Room. */
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    
    /** Foreign key to the patient receiving the vaccine. */
    @ColumnInfo(name = "patient_id") val patientId: Int,
    
    /** Name of the vaccine, e.g. "BCG", "Penta-1". */
    @ColumnInfo(name = "vaccine_name") val vaccineName: String,
    
    /** Dose number of the vaccine. */
    @ColumnInfo(name = "dose_number") val doseNumber: Int = 1,
    
    /** Scheduled date for the vaccine in ISO format. */
    @ColumnInfo(name = "scheduled_date") val scheduledDate: String,
    
    /** Date the vaccine was administered in ISO format. */
    @ColumnInfo(name = "administered_date") val administeredDate: String? = null,
    
    /** Foreign key to the user who administered the vaccine. */
    @ColumnInfo(name = "administered_by") val administeredBy: Int? = null,
    
    /** Batch number of the administered vaccine. */
    @ColumnInfo(name = "batch_number") val batchNumber: String? = null,
    
    /** Status of the vaccination: PENDING/GIVEN/MISSED/OVERDUE. */
    @ColumnInfo(name = "status") val status: String = "PENDING",
    
    /** Additional notes regarding the vaccination. */
    @ColumnInfo(name = "notes") val notes: String? = null,
    
    /** Indicates if the record has been synced to the remote server. */
    @ColumnInfo(name = "is_synced") val isSynced: Boolean = false,
    
    /** Timestamp when the record was created. */
    @ColumnInfo(name = "created_at") val createdAt: String
)
